=== yamada-ui/yamada-ui/www/public/registry/v2/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "dependencies": {
      "type": "object",
      "description": "The dependencies of the registry.",
      "properties": {
        "externals": {
          "type": "array",
          "description": "The externals that the registry depends on.",
          "items": {
            "type": "string"
          }
        },
        "components": {
          "type": "array",
          "description": "The components that the registry depends on.",
          "items": {
            "type": "string"
          }
        },
        "hooks": {
          "type": "array",
          "description": "The hooks that the registry depends on.",
          "items": {
            "type": "string"
          }
        },
        "providers": {
          "type": "array",
          "description": "The providers that the registry depends on.",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["externals", "components", "hooks", "providers"]
    },
    "dependents": {
      "type": "object",
      "description": "The dependents of the registry.",
      "properties": {
        "components": {
          "type": "array",
          "description": "The components that depend on the registry.",
          "items": {
            "type": "string"
          }
        },
        "hooks": {
          "type": "array",
          "description": "The hooks that depend on the registry.",
          "items": {
            "type": "string"
          }
        },
        "providers": {
          "type": "array",
          "description": "The providers that depend on the registry.",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["components", "hooks", "providers"]
    },
    "headless": {
      "type": "boolean",
      "default": false,
      "description": "Whether the registry styles are generated empty."
    },
    "section": {
      "type": "string",
      "description": "The section of the registry.",
      "enum": ["components", "hooks", "providers", "root", "theme"]
    },
    "sources": {
      "type": "array",
      "description": "The sources of the registry.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the source."
          },
          "content": {
            "type": "string",
            "description": "The content of the source."
          },
          "template": {
            "type": "string",
            "description": "The template of the source."
          },
          "data": {
            "type": "array",
            "description": "The data of the source.",
            "items": {
              "type": "object"
            }
          }
        },
        "required": ["name"]
      }
    },
    "tag": {
      "type": "string",
      "description": "The tag of the package.",
      "enum": ["dev", "next"]
    }
  },
  "required": ["section", "sources"]
}

=== yamada-ui/yamada-ui/www/public/registry/next/v2/components/card.json
{
  "$schema": "https://yamada-ui.com/registry/v2/schema.json",
  "dependencies": {
    "components": [],
    "externals": [],
    "hooks": [],
    "providers": []
  },
  "section": "components",
  "sources": [
    {
      "name": "card.style.ts",
      "content": "import { defineComponentSlotStyle } from \"@yamada-ui/react\"\n\nexport const cardStyle = defineComponentSlotStyle({\n  base: {\n    body: {\n      alignItems: \"start\",\n      display: \"flex\",\n      flex: \"1\",\n      flexDirection: \"column\",\n    },\n    footer: {\n      alignItems: \"center\",\n      display: \"flex\",\n      justifyContent: \"start\",\n    },\n    header: {\n      alignItems: \"center\",\n      display: \"flex\",\n      justifyContent: \"start\",\n    },\n    root: {\n      display: \"flex\",\n      flexDirection: \"column\",\n      overflowWrap: \"break-word\",\n      rounded: \"l2\",\n      w: \"full\",\n    },\n  },\n\n  variants: {\n    elevated: {\n      root: {\n        bg: \"bg.panel\",\n        boxShadow: \"md\",\n      },\n    },\n    outline: {\n      root: {\n        layerStyle: \"outline\",\n      },\n    },\n    panel: {\n      root: {\n        layerStyle: \"panel\",\n      },\n    },\n    solid: {\n      root: {\n        layerStyle: \"solid\",\n      },\n    },\n    subtle: {\n      root: {\n        layerStyle: \"subtle\",\n      },\n    },\n    surface: {\n      root: {\n        layerStyle: \"surface\",\n      },\n    },\n  },\n\n  sizes: {\n    sm: {\n      body: { gap: \"3\", px: \"3\", py: \"2\" },\n      footer: { gap: \"3\", pb: \"2\", px: \"3\" },\n      header: { fontSize: \"lg\", gap: \"3\", pt: \"2\", px: \"3\" },\n    },\n    md: {\n      body: { gap: \"4\", px: \"4\", py: \"3\" },\n      footer: { gap: \"4\", pb: \"3\", px: \"4\" },\n      header: { fontSize: \"xl\", gap: \"4\", pt: \"3\", px: \"4\" },\n    },\n    lg: {\n      body: { gap: \"6\", px: \"6\", py: \"5\" },\n      footer: { gap: \"6\", pb: \"5\", px: \"6\" },\n      header: { fontSize: \"2xl\", gap: \"6\", pt: \"5\", px: \"6\" },\n    },\n    xl: {\n      body: { gap: \"8\", px: \"8\", py: \"7\" },\n      footer: { gap: \"8\", pb: \"7\", px: \"8\" },\n      header: { fontSize: \"2xl\", gap: \"8\", pt: \"7\", px: \"8\" },\n    },\n  },\n\n  defaultProps: {\n    size: \"md\",\n    variant: \"panel\",\n  },\n})\n\nexport type CardStyle = typeof cardStyle\n"
    },
    {
      "name": "card.tsx",
      "content": "\"use client\"\n\nimport type { HTMLStyledProps, ThemeProps } from \"@yamada-ui/react\"\nimport type { CardStyle } from \"./card.style\"\nimport { createSlotComponent } from \"@yamada-ui/react\"\nimport { cardStyle } from \"./card.style\"\n\nexport interface CardRootProps\n  extends HTMLStyledProps<\"article\">, ThemeProps<CardStyle> {}\n\nconst {\n  PropsContext: CardPropsContext,\n  usePropsContext: useCardPropsContext,\n  withContext,\n  withProvider,\n} = createSlotComponent<CardRootProps, CardStyle>(\"card\", cardStyle)\n\nexport { CardPropsContext, useCardPropsContext }\n\n/**\n * `Card` is a component that groups and displays related information. By default, it renders a `article` element.\n *\n * @see https://yamada-ui.com/docs/components/card\n */\nexport const CardRoot = withProvider(\"article\", \"root\")()\n\nexport interface CardHeaderProps extends HTMLStyledProps<\"header\"> {}\n\nexport const CardHeader = withContext(\"header\", \"header\")()\n\nexport interface CardBodyProps extends HTMLStyledProps {}\n\nexport const CardBody = withContext(\"div\", \"body\")()\n\nexport interface CardFooterProps extends HTMLStyledProps<\"footer\"> {}\n\nexport const CardFooter = withContext(\"footer\", \"footer\")()\n"
    },
    {
      "name": "index.ts",
      "content": "export * from \"./card.style\"\nexport {\n  CardBody,\n  CardFooter,\n  CardHeader,\n  CardPropsContext,\n  CardRoot,\n  useCardPropsContext,\n} from \"./card\"\nexport type {\n  CardBodyProps,\n  CardFooterProps,\n  CardHeaderProps,\n  CardRootProps,\n} from \"./card\"\nexport * as Card from \"./namespace\"\n"
    },
    {
      "name": "namespace.ts",
      "content": "export type {\n  CardBodyProps as BodyProps,\n  CardFooterProps as FooterProps,\n  CardHeaderProps as HeaderProps,\n  CardRootProps as RootProps,\n} from \"./card\"\nexport {\n  CardBody as Body,\n  CardFooter as Footer,\n  CardHeader as Header,\n  CardPropsContext as PropsContext,\n  CardRoot as Root,\n  useCardPropsContext as usePropsContext,\n} from \"./card\"\n"
    }
  ],
  "tag": "next"
}

=== yamada-ui/yamada-ui/www/public/registry/v2/components/focus-lock.json
{
  "$schema": "https://yamada-ui.com/registry/v2/schema.json",
  "dependencies": {
    "components": [],
    "externals": ["react-focus-lock@^2.13.7"],
    "hooks": [],
    "providers": []
  },
  "dependents": {
    "components": ["drawer", "modal"],
    "hooks": [],
    "providers": []
  },
  "section": "components",
  "sources": [
    {
      "name": "focus-lock.test.browser.tsx",
      "content": "import { useRef, useState } from \"react\"\nimport { page, render, renderHook } from \"#test/browser\"\nimport { FocusLock } from \"./focus-lock\"\n\ndescribe(\"<FocusLock />\", () => {\n  test(\"correctly focuses on elements within the lock\", async () => {\n    await render(\n      <>\n        <button>Not Focused Button</button>\n        <FocusLock>\n          <button>Focused Button</button>\n        </FocusLock>\n      </>,\n    )\n\n    const notFocusedBtn = page.getByRole(\"button\", {\n      name: \"Not Focused Button\",\n      exact: true,\n    })\n    const focusedBtn = page.getByRole(\"button\", {\n      name: \"Focused Button\",\n      exact: true,\n    })\n\n    focusedBtn.element().focus()\n    await expect.element(focusedBtn).toHaveFocus()\n\n    notFocusedBtn.element().focus()\n    await expect.element(focusedBtn).toHaveFocus()\n  })\n\n  test(\"correctly focuses on the button with a reference when initialized\", async () => {\n    const { result } = await renderHook(() => useRef(null))\n\n    await render(\n      <FocusLock initialFocusRef={result.current}>\n        <button>Not Focused Button</button>\n        <button ref={result.current}>Focused Button</button>\n      </FocusLock>,\n    )\n\n    const focusedBtn = page.getByRole(\"button\", {\n      name: \"Focused Button\",\n      exact: true,\n    })\n    await expect.element(focusedBtn).toHaveFocus()\n  })\n\n  test(\"correctly focuses on contentRef when no focusable elements exist\", async () => {\n    const { result } = await renderHook(() => useRef(null))\n\n    await render(\n      <FocusLock contentRef={result.current}>\n        {/* eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex */}\n        <div ref={result.current} tabIndex={0}>\n          No focusable elements here\n        </div>\n      </FocusLock>,\n    )\n\n    const contentDiv = page.getByText(\"No focusable elements here\")\n    await expect.element(contentDiv).toHaveFocus()\n  })\n\n  test(\"correctly focuses on the finalFocusRef when the FocusLock is unmounted\", async () => {\n    const TestComponent = () => {\n      const [isMounted, setIsMounted] = useState(true)\n      const outsideButtonRef = useRef<HTMLButtonElement>(null)\n\n      return (\n        <div>\n          <button ref={outsideButtonRef}>Outside Button</button>\n\n          {isMounted ? (\n            <FocusLock finalFocusRef={outsideButtonRef}>\n              <button>Focus Lock Button</button>\n            </FocusLock>\n          ) : null}\n\n          <button onClick={() => setIsMounted(false)}>\n            Unmount FocusLock Button\n          </button>\n        </div>\n      )\n    }\n\n    const { user } = await render(<TestComponent />)\n\n    const focusLockButton = page.getByRole(\"button\", {\n      name: \"Focus Lock Button\",\n    })\n    const outsideButton = page.getByRole(\"button\", { name: \"Outside Button\" })\n    const unmountButton = page.getByRole(\"button\", {\n      name: \"Unmount FocusLock Button\",\n    })\n\n    focusLockButton.element().focus()\n    await expect.element(focusLockButton).toHaveFocus()\n\n    await user.click(unmountButton)\n\n    await expect.element(outsideButton).toHaveFocus()\n  })\n})\n"
    },
    {
      "name": "focus-lock.tsx",
      "content": "\"use client\"\n\nimport type { FC, PropsWithChildren, RefObject } from \"react\"\nimport { useCallback } from \"react\"\nimport ReactFocusLock from \"react-focus-lock\"\nimport { getFocusableElements, interopDefault } from \"@yamada-ui/react\"\n\nconst InternalFocusLock = interopDefault(ReactFocusLock)\n\nexport interface FocusLockProps extends PropsWithChildren {\n  /**\n   * If `true`, the first focusable element within the `children` will auto-focused once `FocusLock` mounts.\n   *\n   * @default false\n   */\n  autoFocus?: boolean\n  /**\n   * The `ref` of the wrapper for which the focus-lock wraps.\n   */\n  contentRef?: RefObject<HTMLElement | null>\n  /**\n   * If `true`, focus trapping will be disabled.\n   *\n   * @default false\n   */\n  disabled?: boolean\n  /**\n   * `ref` of the element to return focus to when `FocusLock` unmounts.\n   */\n  finalFocusRef?: RefObject<HTMLElement | null>\n  /**\n   * `ref` of the element to receive focus initially.\n   */\n  initialFocusRef?: RefObject<HTMLElement | null>\n  /**\n   * Enables aggressive focus capturing within iframes.\n   * - If `true`: keep focus in the lock, no matter where lock is active.\n   * - If `false`:  allows focus to move outside of iframe.\n   *\n   * @default false\n   */\n  lockFocusAcrossFrames?: boolean\n  /**\n   * If `true`, disables text selections inside, and outside focus lock.\n   *\n   * @default false\n   */\n  persistentFocus?: boolean\n  /**\n   * If `true`, focus will be restored to the element that triggered the `FocusLock` once it unmounts.\n   *\n   * @default false\n   */\n  restoreFocus?: boolean\n}\n\n/**\n * `FocusLock` is a component that improves accessibility by restricting focus within elements such as modals and dialogs, and locking the focus within that range.\n *\n * @see https://yamada-ui.com/docs/components/focus-lock\n */\nexport const FocusLock: FC<FocusLockProps> = ({\n  autoFocus,\n  children,\n  contentRef,\n  disabled,\n  finalFocusRef,\n  initialFocusRef,\n  lockFocusAcrossFrames,\n  persistentFocus,\n  restoreFocus,\n}) => {\n  const returnFocus = restoreFocus && !finalFocusRef\n\n  const onActivation = useCallback(() => {\n    if (initialFocusRef?.current) {\n      initialFocusRef.current.focus()\n    } else if (contentRef?.current) {\n      const focusables = getFocusableElements(contentRef.current)\n\n      if (focusables.length === 0)\n        requestAnimationFrame(() => {\n          contentRef.current?.focus()\n        })\n    }\n  }, [initialFocusRef, contentRef])\n\n  const onDeactivation = useCallback(() => {\n    finalFocusRef?.current?.focus()\n  }, [finalFocusRef])\n\n  return (\n    <InternalFocusLock\n      autoFocus={autoFocus}\n      crossFrame={lockFocusAcrossFrames}\n      disabled={disabled}\n      persistentFocus={persistentFocus}\n      returnFocus={returnFocus}\n      onActivation={onActivation}\n      onDeactivation={onDeactivation}\n    >\n      {children}\n    </InternalFocusLock>\n  )\n}\n"
    },
    {
      "name": "index.ts",
      "content": "export { FocusLock } from \"./focus-lock\"\nexport type { FocusLockProps } from \"./focus-lock\"\n"
    }
  ]
}

=== yamada-ui/yamada-ui/www/public/registry/dev/v2/components/airy.json
{
  "$schema": "https://yamada-ui.com/registry/v2/schema.json",
  "dependencies": {
    "components": ["motion"],
    "externals": ["motion@^12.38.0"],
    "hooks": ["use-controllable-state"],
    "providers": []
  },
  "section": "components",
  "sources": [
    {
      "name": "airy.style.ts",
      "content": "import { defineComponentStyle } from \"@yamada-ui/react\"\n\nexport const airyStyle = defineComponentStyle({\n  base: {\n    opacity: 1,\n    rounded: \"l1\",\n    userSelect: \"none\",\n    width: \"fit-content\",\n    _readOnly: {\n      layerStyle: \"readOnly\",\n    },\n    _disabled: {\n      layerStyle: \"disabled\",\n    },\n  },\n})\n\nexport type AiryStyle = typeof airyStyle\n"
    },
    {
      "name": "airy.test.browser.tsx",
      "content": "import type { KeyframeIdent } from \"@yamada-ui/react\"\nimport { useState } from \"react\"\nimport { a11y, page, render } from \"#test/browser\"\nimport { Airy } from \".\"\n\ndescribe(\"<Airy />\", () => {\n  test(\"should have no accessibility violations\", async () => {\n    await a11y(<Airy from=\"ON\" to=\"OFF\" />)\n  })\n\n  test(\"should render Airy with value and onChange\", async () => {\n    const TestComponent = () => {\n      const [value, onChange] = useState<KeyframeIdent>(\"to\")\n\n      return <Airy from=\"ON\" to=\"OFF\" value={value} onChange={onChange} />\n    }\n\n    const { user } = await render(<TestComponent />)\n\n    const button = page.getByRole(\"button\")\n    await expect.element(button).toHaveAttribute(\"data-value\", \"to\")\n\n    await user.click(button)\n\n    await expect.element(button).toHaveAttribute(\"data-value\", \"from\")\n  })\n\n  test(\"should be read only\", async () => {\n    const { user } = await render(<Airy from=\"ON\" readOnly to=\"OFF\" />)\n\n    const button = page.getByRole(\"button\")\n    await expect.element(button).toHaveAttribute(\"data-readonly\")\n    await expect.element(button).toHaveAttribute(\"data-value\", \"from\")\n    await expect.element(button).toHaveTextContent(\"ON\")\n\n    await user.click(button)\n\n    await expect.element(button).toHaveAttribute(\"data-value\", \"from\")\n    await expect.element(button).toHaveTextContent(\"ON\")\n  })\n})\n"
    },
    {
      "name": "airy.tsx",
      "content": "\"use client\"\n\nimport type { ReactNode } from \"react\"\nimport type { KeyframeIdent, ThemeProps } from \"@yamada-ui/react\"\nimport type { HTMLMotionProps } from \"../motion\"\nimport type { AiryStyle } from \"./airy.style\"\nimport { useAnimation } from \"motion/react\"\nimport { useCallback } from \"react\"\nimport { createComponent,\n  useInjectVarsIntoCss,\n  useInjectVarsIntoProps, dataAttr, handlerAll } from \"@yamada-ui/react\"\nimport { useControllableState } from \"../../hooks/use-controllable-state\"\nimport { motion } from \"../motion\"\nimport { airyStyle } from \"./airy.style\"\n\nexport interface AiryProps\n  extends Omit<HTMLMotionProps<\"button\">, \"onChange\">, ThemeProps<AiryStyle> {\n  /**\n   * Passing React elements to \"from\" is required.\n   */\n  from: ReactNode\n  /**\n   * Passing React elements to \"to\" is required.\n   */\n  to: ReactNode\n  /**\n   * You can set the initial state.\n   *\n   * @default 'from'\n   */\n  defaultValue?: KeyframeIdent\n  /**\n   * The animation delay.\n   *\n   * @default 0\n   */\n  delay?: number\n  /**\n   * If `true`, the component is disabled.\n   *\n   * @default false\n   */\n  disabled?: boolean\n  /**\n   * The animation duration.\n   *\n   * @default 0.2\n   */\n  duration?: number\n  /**\n   * If `true`, the component is readonly.\n   *\n   * @default false\n   */\n  readOnly?: boolean\n  /**\n   * Use this when you want to control the animation from outside the component.\n   */\n  value?: KeyframeIdent\n  /**\n   * This is a callback function that is called when the animation state changes.\n   */\n  onChange?: (value: KeyframeIdent) => void\n}\n\nconst {\n  PropsContext: AiryPropsContext,\n  usePropsContext: useAiryPropsContext,\n  withContext,\n} = createComponent<AiryProps, AiryStyle>(\"airy\", airyStyle)\n\nexport { AiryPropsContext, useAiryPropsContext }\n\n/**\n * `Airy` is a component that creates an airy animation, switching between two elements when one is clicked.\n *\n * @see https://yamada-ui.com/docs/components/airy\n */\nexport const Airy = withContext<\"button\", AiryProps>(\n  ({\n    defaultValue = \"from\",\n    delay = 0,\n    disabled,\n    duration = 0.2,\n    from,\n    readOnly,\n    to,\n    value: valueProp,\n    onChange,\n    onClick: onClickProp,\n    ...rest\n  }) => {\n    const opacity = \"var(--opacity)\"\n    const animate = useAnimation()\n    const [value, setValue] = useControllableState<KeyframeIdent>({\n      defaultValue,\n      value: valueProp,\n      onChange,\n    })\n\n    const onClick = useCallback(async () => {\n      if (readOnly) return\n\n      await animate.start({ opacity: 0, transition: { delay, duration } })\n\n      setValue((prev) => (prev === \"from\" ? \"to\" : \"from\"))\n\n      await animate.start({ opacity, transition: { duration } })\n    }, [animate, setValue, readOnly, opacity, duration, delay])\n\n    return (\n      <motion.button\n        type=\"button\"\n        data-disabled={dataAttr(disabled)}\n        data-readonly={dataAttr(readOnly)}\n        data-value={value}\n        animate={animate}\n        disabled={disabled}\n        initial={{ opacity }}\n        onClick={handlerAll(onClickProp, onClick)}\n        {...rest}\n      >\n        {value === \"from\" ? from : to}\n      </motion.button>\n    )\n  },\n)(undefined, (props) => {\n  const css = useInjectVarsIntoCss(props.css, { opacity: \"opacity\" })\n  const rest = useInjectVarsIntoProps(props, { opacity: \"opacity\" })\n\n  return { ...rest, css, opacity: \"{opacity}\" }\n})\n"
    },
    {
      "name": "index.ts",
      "content": "export * from \"./airy.style\"\nexport { Airy, AiryPropsContext, useAiryPropsContext } from \"./airy\"\nexport type { AiryProps } from \"./airy\"\n"
    }
  ],
  "tag": "dev"
}

=== yamada-ui/yamada-ui/www/public/registry/next/v2/components/indicator.json
{
  "$schema": "https://yamada-ui.com/registry/v2/schema.json",
  "dependencies": {
    "components": ["float"],
    "externals": [],
    "hooks": [],
    "providers": []
  },
  "section": "components",
  "sources": [
    {
      "name": "index.ts",
      "content": "export * from \"./indicator.style\"\nexport {\n  Indicator,\n  IndicatorPropsContext,\n  useIndicatorPropsContext,\n} from \"./indicator\"\nexport type { IndicatorProps } from \"./indicator\"\n"
    },
    {
      "name": "indicator.style.ts",
      "content": "import { defineComponentSlotStyle } from \"@yamada-ui/react\"\n\nexport const indicatorStyle = defineComponentSlotStyle({\n  base: {\n    float: {\n      zIndex: \"yamcha\",\n    },\n    label: {\n      alignItems: \"center\",\n      display: \"inline-flex\",\n      rounded: \"full\",\n      verticalAlign: \"middle\",\n      whiteSpace: \"nowrap\",\n      _numeric: {\n        fontWeight: \"medium\",\n      },\n    },\n    root: {\n      position: \"relative\",\n    },\n  },\n\n  props: {\n    /**\n     * If `true`, set the indicator as an inline element.\n     *\n     * @default false\n     * */\n    inline: {\n      false: {\n        root: {\n          display: \"block\",\n        },\n      },\n      true: {\n        root: {\n          display: \"inline-block\",\n        },\n      },\n    },\n    /**\n     * If `true`, make an element scale and fade like a radar ping or ripple of water.\n     *\n     * @default false\n     */\n    ping: {\n      true: {\n        label: {\n          _before: {\n            animationDuration: \"{duration, 1.4s}\",\n            animationFillMode: \"forwards\",\n            animationIterationCount: \"{iteration-count, infinite}\",\n            animationName: \"ping\",\n            animationTimingFunction:\n              \"{timing-function, cubic-bezier(0, 0, 0.2, 1)}\",\n            bg: \"{ping-color}\",\n            boxSize: \"100%\",\n            inset: \"0\",\n            opacity: 0.7,\n            position: \"absolute\",\n            rounded: \"full\",\n            zIndex: -1,\n          },\n        },\n        root: {\n          \"--animation-scale\": \"1.8\",\n        },\n      },\n    },\n    /**\n     * If `true`, display the border of the indicator.\n     *\n     * @default false\n     */\n    withBorder: {\n      true: {\n        label: {\n          borderColor: [\"white\", \"black\"],\n          borderWidth: \"0.2em\",\n        },\n      },\n    },\n  },\n\n  variants: {\n    solid: {\n      label: {\n        layerStyle: \"solid\",\n        \"--ping-color\": \"colorScheme.outline\",\n      },\n    },\n    subtle: {\n      label: {\n        layerStyle: \"subtle\",\n        \"--ping-color\": \"colorScheme.outline\",\n      },\n    },\n    surface: {\n      label: {\n        layerStyle: \"surface\",\n        \"--ping-color\": \"colorScheme.outline\",\n      },\n    },\n  },\n\n  sizes: {\n    sm: {\n      label: {\n        fontSize: \"xs\",\n        minBoxSize: \"3\",\n        _notEmpty: { px: \"1.5\" },\n      },\n    },\n    md: {\n      label: {\n        fontSize: \"sm\",\n        minBoxSize: \"4\",\n        _notEmpty: { px: \"2\" },\n      },\n    },\n    lg: {\n      label: {\n        fontSize: \"md\",\n        minBoxSize: \"5\",\n        _notEmpty: { px: \"2.5\" },\n      },\n    },\n  },\n\n  defaultProps: {\n    size: \"sm\",\n    variant: \"solid\",\n    ping: false,\n  },\n})\n\nexport type IndicatorStyle = typeof indicatorStyle\n"
    },
    {
      "name": "indicator.tsx",
      "content": "\"use client\"\n\nimport type { ReactNode } from \"react\"\nimport type { CSSProps, HTMLStyledProps, ThemeProps } from \"@yamada-ui/react\"\nimport type { FloatProps } from \"../float\"\nimport type { IndicatorStyle } from \"./indicator.style\"\nimport { useMemo } from \"react\"\nimport { createSlotComponent, styled, varAttr, dataAttr, isNumber, isObject } from \"@yamada-ui/react\"\nimport { Float } from \"../float\"\nimport { indicatorStyle } from \"./indicator.style\"\n\ninterface PingOptions {\n  /**\n   * It is used for the color of the ping animation.\n   */\n  color?: CSSProps[\"backgroundColor\"]\n  /**\n   * It is used for the duration of the ping animation.\n   */\n  duration?: CSSProps[\"animationDuration\"]\n  /**\n   * It is used for the count of the ping animation.\n   */\n  iterationCount?: CSSProps[\"animationIterationCount\"]\n  /**\n   * It is used for the scale of the ping animation.\n   */\n  scale?: CSSProps[\"scale\"]\n  /**\n   * It is used for the timing function of the ping animation.\n   */\n  timingFunction?: CSSProps[\"animationTimingFunction\"]\n}\n\nexport interface IndicatorProps\n  extends\n    Omit<HTMLStyledProps, \"offset\">,\n    Omit<ThemeProps<IndicatorStyle>, \"ping\">,\n    Pick<FloatProps, \"offset\" | \"placement\"> {\n  /**\n   * If `true`, the indicator will be disabled.\n   *\n   * @default false\n   */\n  disabled?: boolean\n  /**\n   * The indicator label to use.\n   */\n  label?: ReactNode\n  /**\n   * If `label` is of type number, the maximum number displayed.\n   *\n   * @default 99\n   */\n  overflowCount?: number\n  /**\n   * If `true`, make an element scale and fade like a radar ping or ripple of water.\n   *\n   * @default false\n   */\n  ping?: boolean | PingOptions\n  /**\n   * If `true`, display 0.\n   *\n   * @default true\n   */\n  showZero?: boolean\n  /**\n   * Props for the float element.\n   */\n  floatProps?: IndicatorFloatProps\n  /**\n   * Props for the label element.\n   */\n  labelProps?: IndicatorLabelProps\n}\n\nconst {\n  PropsContext: IndicatorPropsContext,\n  usePropsContext: useIndicatorPropsContext,\n  withContext,\n  withProvider,\n} = createSlotComponent<IndicatorProps, IndicatorStyle>(\n  \"indicator\",\n  indicatorStyle,\n)\n\nexport { IndicatorPropsContext, useIndicatorPropsContext }\n\n/**\n * `Indicator` is a component that displays at the corner of elements such as avatars.\n *\n * @see https://yamada-ui.com/docs/components/indicator\n */\nexport const Indicator = withProvider(\n  ({\n    children,\n    disabled,\n    label,\n    offset,\n    overflowCount = 99,\n    placement,\n    showZero = true,\n    floatProps,\n    labelProps,\n    ...rest\n  }) => {\n    const numeric = isNumber(label)\n\n    disabled ??= numeric && !showZero && label <= 0\n\n    const computedLabel = useMemo(() => {\n      if (numeric && label > overflowCount) {\n        return (\n          <>\n            {overflowCount}\n            <styled.span>+</styled.span>\n          </>\n        )\n      } else {\n        return label\n      }\n    }, [numeric, label, overflowCount])\n\n    return (\n      <styled.div {...rest}>\n        {children}\n\n        {!disabled ? (\n          <IndicatorFloat offset={offset} placement={placement} {...floatProps}>\n            <IndicatorLabel data-numeric={dataAttr(numeric)} {...labelProps}>\n              {computedLabel}\n            </IndicatorLabel>\n          </IndicatorFloat>\n        ) : null}\n      </styled.div>\n    )\n  },\n  \"root\",\n)(({ ping, ...rest }) => {\n  if (isObject(ping)) {\n    const { color, duration, iterationCount, scale, timingFunction } = ping\n\n    return {\n      ...rest,\n      \"--animation-scale\": scale,\n      \"--duration\": varAttr(duration, \"durations\"),\n      \"--iteration-count\": iterationCount,\n      \"--ping-color\": varAttr(color, \"colors\"),\n      \"--timing-function\": varAttr(timingFunction, \"easings\"),\n      ping: true,\n    }\n  } else {\n    return { ...rest, ping }\n  }\n})\n\ninterface IndicatorFloatProps extends FloatProps {}\n\nconst IndicatorFloat = withContext<\"div\", IndicatorFloatProps>(Float, \"float\")()\n\ninterface IndicatorLabelProps extends HTMLStyledProps<\"span\"> {}\n\nconst IndicatorLabel = withContext<\"span\", IndicatorLabelProps>(\n  \"span\",\n  \"label\",\n)()\n"
    }
  ],
  "tag": "next"
}
